### ISSUE TITLE
Invalid presets

### ISSUE THREAD

**Issue by don-vip** [depth221/Preset-Franchises_in_Korea#1]
Hello,
Your presets trigger an error in JOSM integration test:
`
org.xml.sax.SAXParseException; lineNumber: 125; columnNumber: 7; The element type "reference" must be terminated by the matching end-tag "</reference>".`

**Comment by don-vip** [comment]
Can you please fix this issue? We can't keep invalid presets in the default list.

**Comment by don-vip** [comment]
Presets [removed](https://josm.openstreetmap.de/wiki/PresetsSource?action=diff&version=70&old_version=69).

**Comment by depth221** [comment]
@don-vip Sorry, I didn't know my preset have errors because I didn't remove my cache, and just have solved the bugs. Thus I will relocate my preset in the default list.

**Comment by don-vip** [comment]
Thanks!
