### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by stoecker** [depth221/Preset-Franchises_in_Korea#2]
Hello,

in JOSM we try to use HTTPS as much as possible. This preset uses a lot of URLs which support HTTPS. See the JOSM ticket
https://josm.openstreetmap.de/ticket/16123

Usually everythong with PRESET:Presets.zip behind and where "200 OK" is can be switched to HTTPS.

**Comment by stoecker** [comment]
Ping?

**Comment by depth221** [comment]
@stoecker Sorry for lateness. So, What I should do?

**Comment by stoecker** [comment]
Have a look at the links your provide: E.g. like www.burgerking.co.kr they should have https:// instead of http://.

Candidates are the ones listed in https://josm.openstreetmap.de/ticket/16123 (search for PRESET:Preset.zip - if there is "200 OK" before it, it works most of the time, for others it may work). 

Note you need to test each individually, as for some the script says it works, but the page is not really HTTPS-Ready. For others you get an error, but everything is ok (sometimes you need to add www. in front when missing :-).

Each entry switched successfully from http to https is welcome.

**Comment by depth221** [comment]
@stoecker Thanks for detailed explanation!
