### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by Klumbumbus** [depth221/Preset-Franchises_in_Korea#3]
There is an issue with an icon:

`Could not get presets icon Franchises_in_Korea/logo/Starbucks.jpg`

**Comment by depth221** [comment]
I got it, and merged don-vip's PR. Sorry.

**Comment by Klumbumbus** [comment]
The version needs to be increased in the xml and a new zip file needs to be published.

**Comment by depth221** [comment]
@Klumbumbus Oh, sorry. I published the updated zip file just a moment ago.
