### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by Klumbumbus** [depth221/Preset-Franchises_in_Korea#5]
The link to the preset on https://josm.openstreetmap.de/wiki/PresetsSource gives a 404 error ( https://raw.githubusercontent.com/depth221/Preset-Franchises_in_Korea/master/zip/Preset.zip).

**Comment by Klumbumbus** [comment]
Disabled until it is fixed.
https://josm.openstreetmap.de/wiki/PresetsSource?action=diff&version=141

**Comment by depth221** [comment]
I've replaced that link with https://github.com/depth221/Preset-Franchises_in_Korea/raw/master/zip/preset.zip
Thanks!
