### ISSUE TITLE
amenity=embassy is deprecated

### ISSUE THREAD

**Issue by Klumbumbus** [depth221/Preset-Franchises_in_Korea#6]
amenity=embassy is deprecated and the preset should be removed or replaced by the new tagging. Additional the icon presets/service/embassy.svg is no longer available in JOSM. See https://josm.openstreetmap.de/ticket/20338

**Comment by depth221** [comment]
Fortunately, I've never been using the tag for my preset. Thank you for your concerning!

**Comment by Klumbumbus** [comment]
Hm strange. Then I must have been mixed it up with another preset.
